app_name: my-product
environment: production
region: nyc
do_region: nyc3

project:
  name: my-product-production
  environment: production
  purpose: Web Application

github:
  owner: your-github-org
  api_repo: my-product-api
  web_repo: my-product-web
  branch: main
  auto_deploy: true

components:
  api: true
  worker: true
  web: true
  postgres: true
  opensearch: true
  spaces: true

sizes:
  api: basic-xxs
  worker: basic-xxs
  web: basic-xxs
  postgres: db-s-1vcpu-1gb
  opensearch: db-s-1vcpu-2gb

# digitalocean_spaces or aws_s3
spaces_provider: digitalocean_spaces
