---
project:
  name: Product Template Workspace
  slug: product-template-workspace
  installation_id: "000000"
  default_environment: production
repositories:
  api:
    purpose: backend-api
    name: api-template
    path: repos/api-template
    github: scarrick68/api-template
  web:
    purpose: frontend-web-client
    name: web-template
    path: repos/web-template
    github: scarrick68/web-template
services:
  api:
    repository: api
    port: 5001
  web:
    repository: web
    port: 3000
  postgres:
    port: 5432
  opensearch:
    port: 9200
environments:
  production:
    infrastructure:
      provider: digitalocean
      app_name: product-template-workspace
      region: nyc3
      frontend_domain: ''
      github:
        owner: scarrick68
      deployment:
        branch: main
        auto_deploy: true
      components:
        api:
          enabled: true
          service: api
          size: basic-xxs
        worker:
          enabled: true
          service: api
          size: basic-xxs
        web:
          enabled: true
          service: web
          size: basic-xxs
        postgres:
          enabled: true
          size: db-s-1vcpu-1gb
        opensearch:
          enabled: true
          size: db-s-1vcpu-2gb
        spaces:
          enabled: true
          provider: digitalocean_spaces
      app_region: nyc
