repositories:
  - purpose: backend-api
    name: api-template
    path: repos/api-template
    github: scarrick68/api-template

  - purpose: frontend-web-client
    name: web-template
    path: repos/web-template
    github: scarrick68/web-template
