repositories:
  - purpose: backend-api
    name: api-template
    path: repos/api-template
    github: scarrick68/api-template

  - purpose: frontend-web-client
    name: web-template
    path: repos/web-template
    github: scarrick68/web-template

  - purpose: frontend-mobile-client
    name: mobile-app-template
    path: repos/mobile-app-template
    github: scarrick68/mobile-app-template

  - purpose: data-science-ml
    name: dsml-template
    path: repos/dsml-template
    github: scarrick68/dsml-template
    runtime:
      python_version: "3.13"
