# frozen_string_literal: true

require "shellwords"
require_relative "../../../test_helper"

class InitProjectCommandTest < Minitest::Test
  def test_returns_usage_when_slug_missing
    Workspace.stubs(:fail_with_help)

    command = Workspace::Commands::InitProjectCommand.new([])

    assert_equal 1, command.call
  end

  def test_refuses_when_destination_is_workspace_root
    Workspace.stubs(:fail_with_help)

    command = Workspace::Commands::InitProjectCommand.new(["--destination", Workspace::ROOT, "my-super-app"])

    assert_equal 1, command.call
  end

  def test_refuses_when_destination_is_nested_under_workspace
    Workspace.stubs(:fail_with_help)

    nested = File.join(Workspace::ROOT, "tmp", "my-super-app")
    command = Workspace::Commands::InitProjectCommand.new(["--destination", nested, "my-super-app"])

    assert_equal 1, command.call
  end

  def test_refuses_when_destination_already_exists
    destination_root = File.join(File.dirname(Workspace::ROOT), "my-super-app")
    Workspace.stubs(:fail_with_help)
    File.stubs(:exist?).with(destination_root).returns(true)

    command = Workspace::Commands::InitProjectCommand.new(["--destination", destination_root, "my-super-app"])

    assert_equal 1, command.call
  end

  def test_returns_failure_when_destination_flag_has_no_value
    Workspace.stubs(:fail_with_help)

    command = Workspace::Commands::InitProjectCommand.new(["--destination"])

    assert_equal 1, command.call
  end

  def test_copies_workspace_then_runs_init_in_generated_destination
    source_root = Workspace::ROOT
    destination_root = File.join(File.dirname(source_root), "my-super-app")
    init_script = File.join(destination_root, "bin", "init_new_project")

    Workspace.stubs(:section)
    Workspace.stubs(:info)
    Workspace.stubs(:warn)
    Workspace.stubs(:ok)
    Workspace.stubs(:fail_with_help)

    File.stubs(:exist?).with(destination_root).returns(false)
    FileUtils.stubs(:mkdir_p)
    FileUtils.stubs(:cp_r)
    File.stubs(:write)

    FileUtils.expects(:cp_r).with(File.join(source_root, "."), destination_root).once
    File.expects(:write).with(File.join(destination_root, ".generated-project-workspace"), "Generated by bin/init_project\n").once

    Workspace.expects(:run).with(
      "ruby #{Shellwords.escape(init_script)} my-super-app -- --no-dev",
      has_entries(chdir: destination_root, allow_failure: true)
    ).returns(true)

    command = Workspace::Commands::InitProjectCommand.new(["--destination", destination_root, "my-super-app", "--", "--no-dev"])

    assert_equal 0, command.call
  end

  def test_uses_sibling_destination_when_none_is_provided
    source_root = Workspace::ROOT
    destination_root = File.join(File.dirname(source_root), "my-super-app")
    init_script = File.join(destination_root, "bin", "init_new_project")

    Workspace.stubs(:section)
    Workspace.stubs(:info)
    Workspace.stubs(:warn)
    Workspace.stubs(:ok)
    Workspace.stubs(:fail_with_help)

    File.stubs(:exist?).with(destination_root).returns(false)
    FileUtils.stubs(:mkdir_p)
    FileUtils.stubs(:cp_r)
    File.stubs(:write)

    FileUtils.expects(:cp_r).with(File.join(source_root, "."), destination_root).once
    File.expects(:write).with(File.join(destination_root, ".generated-project-workspace"), "Generated by bin/init_project\n").once

    Workspace.expects(:run).with(
      "ruby #{Shellwords.escape(init_script)} my-super-app",
      has_entries(chdir: destination_root, allow_failure: true)
    ).returns(true)

    command = Workspace::Commands::InitProjectCommand.new(["my-super-app"])

    assert_equal 0, command.call
  end
end