# frozen_string_literal: true
require_relative "../../../test_helper"

class NewProjectTest < Minitest::Test
  def test_returns_usage_when_slug_missing
    Workspace.stubs(:fail_with_help)

    command = Workspace::Services::NewProject.new([])

    assert_equal 1, command.call
  end

  def test_refuses_when_destination_is_workspace_root
    Workspace.stubs(:fail_with_help)

    command = Workspace::Services::NewProject.new(["--destination", Workspace::ROOT, "my-super-app"])

    assert_equal 1, command.call
  end

  def test_refuses_when_destination_is_nested_under_workspace
    Workspace.stubs(:fail_with_help)

    nested = File.join(Workspace::ROOT, "tmp", "my-super-app")
    command = Workspace::Services::NewProject.new(["--destination", nested, "my-super-app"])

    assert_equal 1, command.call
  end

  def test_refuses_when_destination_already_exists
    destination_root = File.join(File.dirname(Workspace::ROOT), "my-super-app")
    Workspace.stubs(:fail_with_help)
    File.stubs(:exist?).with(destination_root).returns(true)

    command = Workspace::Services::NewProject.new(["--destination", destination_root, "my-super-app"])

    assert_equal 1, command.call
  end

  def test_returns_failure_when_destination_flag_has_no_value
    Workspace.stubs(:fail_with_help)

    command = Workspace::Services::NewProject.new(["--destination"])

    assert_equal 1, command.call
  end

  def test_copies_workspace_then_runs_init_in_generated_destination
    source_root = Workspace::ROOT
    destination_root = File.join(File.dirname(source_root), "my-super-app")
    init_service = mock("init_new_project")

    Workspace.stubs(:section)
    Workspace.stubs(:info)
    Workspace.stubs(:warn)
    Workspace.stubs(:ok)
    Workspace.stubs(:fail_with_help)

    File.stubs(:exist?).with(destination_root).returns(false)
    FileUtils.stubs(:mkdir_p)
    FileUtils.stubs(:cp_r)
    File.stubs(:write)

    FileUtils.expects(:cp_r).with(File.join(source_root, "."), destination_root).once
    File.expects(:write).with(
      File.join(destination_root, ".generated-project-workspace"),
      "Generated by Workspace::Services::TemplateWorkspaceGenerator\n"
    ).once

    Workspace::Services::InitNewProject.expects(:new).with do |init_args, kwargs|
      init_args == ["my-super-app", "--", "--no-dev"] &&
        kwargs[:context].respond_to?(:root) &&
        kwargs[:context].root == destination_root
    end.returns(init_service)
    init_service.expects(:call).returns(0)

    command = Workspace::Services::NewProject.new(["--destination", destination_root, "my-super-app", "--", "--no-dev"])

    assert_equal 0, command.call
  end

  def test_uses_sibling_destination_when_none_is_provided
    source_root = Workspace::ROOT
    destination_root = File.join(File.dirname(source_root), "my-super-app")
    init_service = mock("init_new_project")

    Workspace.stubs(:section)
    Workspace.stubs(:info)
    Workspace.stubs(:warn)
    Workspace.stubs(:ok)
    Workspace.stubs(:fail_with_help)

    File.stubs(:exist?).with(destination_root).returns(false)
    FileUtils.stubs(:mkdir_p)
    FileUtils.stubs(:cp_r)
    File.stubs(:write)

    FileUtils.expects(:cp_r).with(File.join(source_root, "."), destination_root).once
    File.expects(:write).with(
      File.join(destination_root, ".generated-project-workspace"),
      "Generated by Workspace::Services::TemplateWorkspaceGenerator\n"
    ).once

    Workspace::Services::InitNewProject.expects(:new).with do |init_args, kwargs|
      init_args == ["my-super-app"] &&
        kwargs[:context].respond_to?(:root) &&
        kwargs[:context].root == destination_root
    end.returns(init_service)
    init_service.expects(:call).returns(0)

    command = Workspace::Services::NewProject.new(["my-super-app"])

    assert_equal 0, command.call
  end

  def test_forwards_with_cms_alias_to_init_new_project
    source_root = Workspace::ROOT
    destination_root = File.join(File.dirname(source_root), "my-super-app")
    init_service = mock("init_new_project")

    Workspace.stubs(:section)
    Workspace.stubs(:info)
    Workspace.stubs(:warn)
    Workspace.stubs(:ok)
    Workspace.stubs(:fail_with_help)

    File.stubs(:exist?).with(destination_root).returns(false)
    FileUtils.stubs(:mkdir_p)
    FileUtils.stubs(:cp_r)
    File.stubs(:write)

    FileUtils.expects(:cp_r).with(File.join(source_root, "."), destination_root).once
    File.expects(:write).with(
      File.join(destination_root, ".generated-project-workspace"),
      "Generated by Workspace::Services::TemplateWorkspaceGenerator\n"
    ).once

    Workspace::Services::InitNewProject.expects(:new).with do |init_args, kwargs|
      init_args == ["my-super-app", "--cms=keystatic"] &&
        kwargs[:context].respond_to?(:root) &&
        kwargs[:context].root == destination_root
    end.returns(init_service)
    init_service.expects(:call).returns(0)

    command = Workspace::Services::NewProject.new(["--with-cms", "my-super-app"])

    assert_equal 0, command.call
  end

  def test_returns_failure_for_unsupported_cms_provider
    Workspace.stubs(:fail_with_help)

    command = Workspace::Services::NewProject.new(["--cms=sanity", "my-super-app"])

    assert_equal 1, command.call
  end
end