# frozen_string_literal: true

require_relative "../../../test_helper"
require_relative "../../../../lib/workspace/services/template_workspace_generator"

class TemplateWorkspaceGeneratorTest < Minitest::Test
  def test_copies_workspace_contents_to_destination
    Dir.mktmpdir("template-source-") do |source_root|
      Dir.mktmpdir("template-parent-") do |parent_dir|
        FileUtils.mkdir_p(File.join(source_root, "nested"))
        File.write(File.join(source_root, "nested", "example.txt"), "hello")

        destination_root = File.join(parent_dir, "my-super-app")

        generator = Workspace::Services::TemplateWorkspaceGenerator.new(
          source_root: source_root,
          destination_root: destination_root
        )

        generator.call

        copied_file = File.join(destination_root, "nested", "example.txt")
        assert File.exist?(copied_file), "expected copied file to exist at destination"
        assert_equal "hello", File.read(copied_file)
      end
    end
  end

  def test_writes_generated_workspace_marker
    Dir.mktmpdir("template-source-") do |source_root|
      Dir.mktmpdir("template-parent-") do |parent_dir|
        File.write(File.join(source_root, "README.md"), "source")

        destination_root = File.join(parent_dir, "my-super-app")

        generator = Workspace::Services::TemplateWorkspaceGenerator.new(
          source_root: source_root,
          destination_root: destination_root
        )

        generator.call

        marker_path = File.join(destination_root, ".generated-project-workspace")
        assert File.exist?(marker_path), "expected generated marker file to exist"
        assert_equal "Generated by Workspace::Services::TemplateWorkspaceGenerator\n", File.read(marker_path)
      end
    end
  end
end
