#!/usr/bin/env ruby
# frozen_string_literal: true
# Creates a copied workspace for a new app, then runs init_new_project in the copy.

require "fileutils"
require "optparse"
require "shellwords"
require_relative "../../workspace"

module Workspace
  module Services
    class InitProject
      def initialize(argv, stdin: $stdin, stdout: $stdout)
        @argv = argv.dup
        @stdin = stdin
        @stdout = stdout
      end

      def call
        options = parse_options
        return 1 unless options

        slug = options[:product_slug]
        return usage unless valid_slug?(slug)

        source_root = Workspace::ROOT
        destination_root = File.expand_path(options[:destination] || default_destination_for(slug))

        return 1 unless validate_destination!(source_root, destination_root)

        Workspace.section("Init Project: Copy And Initialize")
        Workspace.info("Source workspace: #{source_root}")
        Workspace.info("Destination workspace: #{destination_root}")

        copy_workspace(source_root, destination_root)
        mark_generated_workspace(destination_root)

        run_generated_workspace_init(destination_root, slug, options[:forwarded_args])
      end

      private

      attr_reader :argv, :stdin, :stdout

      def parse_options
        options = {
          destination: nil,
          forwarded_args: []
        }

        args = argv.dup

        parser = OptionParser.new do |opts|
          opts.on("--destination PATH", "--dest PATH", "Path for generated workspace copy") do |path|
            options[:destination] = path
          end

          opts.on("-h", "--help", "Show usage") do
            return nil
          end
        end

        parser.order!(args)

        options[:product_slug] = args.shift
        options[:forwarded_args] = args

        options
      rescue OptionParser::ParseError => e
        Workspace.fail_with_help(
          "Invalid init_project options.",
          details: e.message,
          fixes: [
            "Usage: bin/init_project [--destination PATH] <product-slug> -- [init_new_project flags...]",
            "Example: bin/init_project --destination ~/Code/my-super-app my-super-app -- --no-dev"
          ]
        )
        nil
      end

      def valid_slug?(value)
        value.to_s.match?(/\A[a-z0-9]+(?:-[a-z0-9]+)*\z/)
      end

      def default_destination_for(slug)
        File.join(File.dirname(Workspace::ROOT), slug)
      end

      def validate_destination!(source_root, destination_root)
        if destination_root == source_root
          Workspace.fail_with_help(
            "Destination must be different from the original cloned template workspace.",
            details: "Source and destination are both #{source_root}",
            fixes: [
              "Choose a different destination path with --destination.",
              "Example: bin/init_project my-super-app --destination ~/Code/my-super-app"
            ]
          )
          return false
        end

        if destination_root.start_with?("#{source_root}/")
          Workspace.fail_with_help(
            "Destination cannot be nested inside the template workspace.",
            details: "Destination: #{destination_root}",
            fixes: [
              "Use a sibling or external destination path.",
              "Example: --destination ~/Code/my-super-app"
            ]
          )
          return false
        end

        return true unless File.exist?(destination_root)

        Workspace.fail_with_help(
          "Destination already exists.",
          details: "Refusing to overwrite existing path: #{destination_root}",
          fixes: [
            "Choose a new destination path.",
            "Remove the existing path only if you are sure it is safe."
          ]
        )
        false
      end

      def copy_workspace(source_root, destination_root)
        Workspace.info("Copying template workspace to destination: #{destination_root}")
        FileUtils.mkdir_p(File.dirname(destination_root))
        FileUtils.cp_r(File.join(source_root, "."), destination_root)
      end

      def mark_generated_workspace(destination_root)
        marker_path = File.join(destination_root, ".generated-project-workspace")
        File.write(marker_path, "Generated by bin/init_project\n")
      end

      def run_generated_workspace_init(destination_root, slug, forwarded_args)
        init_script = File.join(destination_root, "bin", "init_new_project")
        forwarded = forwarded_args.map { |arg| Shellwords.escape(arg) }.join(" ")
        forwarded = " #{forwarded}" unless forwarded.empty?

        command = "ruby #{Shellwords.escape(init_script)} #{Shellwords.escape(slug)}#{forwarded}"

        success = Workspace.run(
          command,
          chdir: destination_root,
          allow_failure: true,
          summary: "Generated workspace initialization failed.",
          details: "Destination: #{destination_root}",
          fixes: [
            "Review output above and resolve the reported issue in the generated workspace.",
            "Retry inside destination: #{Shellwords.escape(init_script)} #{slug}",
            "Template workspace source remains unchanged by this run."
          ]
        )

        return 0 if success

        Workspace.fail("The generated workspace remains at #{destination_root} for inspection and retry.")
        1
      end

      def usage
        Workspace.fail_with_help(
          "Missing or invalid product slug.",
          details: "Usage: bin/init_project [--destination PATH] <product-slug> -- [init_new_project flags...]",
          fixes: [
            "Use kebab-case product slug (example: my-super-app).",
            "Run: bin/init_project my-super-app",
            "Optionally set destination: bin/init_project --destination ~/Code/my-super-app my-super-app",
            "Forward flags to init_new_project after --, for example: -- --no-dev"
          ]
        )
        1
      end
    end
  end
end