# frozen_string_literal: true

require "fileutils"
require_relative "../../workspace"
# This service is responsible for copying the template workspace into a new 
# destination workspace, and marking it as generated to distinguish it from the base template.

module Workspace
  module Services
    class TemplateWorkspaceGenerator
      def initialize(source_root: Workspace::ROOT, destination_root:)
        @source_root = source_root
        @destination_root = destination_root
      end

      def call
        copy_workspace
        mark_workspace_as_generated
      end

      private

      attr_reader :source_root, :destination_root

      def copy_workspace
        Workspace.info("Copying template workspace to destination: #{destination_root}")
        FileUtils.mkdir_p(File.dirname(destination_root))
        FileUtils.cp_r(File.join(source_root, "."), destination_root)
      end

      def mark_workspace_as_generated
        marker_path = File.join(destination_root, ".generated-project-workspace")
        File.write(marker_path, "Generated by #{self.class.name}\n")
      end
    end
  end
end
